scriptname SLNC_ConfigGroup_CommonAnimTagList extends SLNC_ConfigGroup_AnimTagList hidden

; SLNC_ConfigGroup_AnimTagList
SLNC_AnimTagList function GetTagList()
  return Menu.System.CommonAnimationTagList
endFunction
