scriptname SLNC_ConfigGroup_VaginalAnimTagList extends SLNC_ConfigGroup_AnimTagList hidden

; SLNC_ConfigGroup_AnimTagList
SLNC_AnimTagList function GetTagList()
  return Menu.System.VaginalAnimationTagList
endFunction
